# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stackoverflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=255)),
                ('tags', models.TextField()),
                ('link', models.IntegerField()),
                ('views', models.IntegerField()),
                ('answers', models.IntegerField()),
                ('votes', models.IntegerField()),
            ],
        ),
    ]
